version: "3.9"

services:
  datanode:
    image: yarivgraf/apache-hadoop-3.2.2:latest
    volumes:
      - /var/lib/hadoop-hdfs/cache/hdfs/dfs/name:/var/lib/hadoop-hdfs/cache/hdfs/dfs/name
    restart: always
    container_name: datanode
    extra_hosts:
      - "namenode:10.240.0.57"
    networks:
      namenode-network:
        ipv4_address: 10.5.0.4
    command: "/run-datanode.sh"

  impalad:
    depends_on:
      - datanode
    image: yarivgraf/apache-impala-3.4.0:compose
    restart: always
    extra_hosts:
      - "catalogd:10.240.0.57"
      - "statestored:10.240.0.57"
    volumes:
      - "/opt/impala/logs:/opt/impala/logs"
    container_name: impalad
    ports:
      - "25000:25000"
    environment:
      IP: 0.0.0.0
    networks:
      namenode-network:
        ipv4_address: 10.5.0.7
    command: "/entrypoint_impalad.sh"
networks:
      namenode-network:
        driver: bridge
        ipam:
         driver: default
         config:
           - subnet: 10.5.0.0/24

